name=easyMenu
version=1.0.0
author=Holman Buenaventura
maintainer=Holman Buenaventura
sentence=Library to create and manage menus easily supports Adafruit and u8g2 drivers
paragraph=easyMenu allows you to create multi-level menus simply and intuitively. It features memory management to prevent fragmentation, callbacks for button assignment, a marquee (automatic horizontal scrolling) for long options, and adaptive line spacing based on screen height. Compatible with U8g2 and Adafruit_GFX.
category=Display
url=https://github.com/habuenav/easyMenu
architectures=*
depends=
